Config.Hazards = Config.Hazards or {}
Config.Zones = Config.Zones or {}
Config.ClientFx = Config.ClientFx or {}
Disasters = Disasters or {}

Config.Hazards.tornado = {
    enabled = true,
    pullRadius = 120.0,
    lethalCoreRadius = 10.0,
    maxForceDistance = 105.0,
    vehicleEngineStallChance = 0.20,
    debrisDamage = 4,
    movement = {
        enabled = true,
        minSpeed = 1.0,
        maxSpeed = 4.0,
        turnIntervalMinMs = 3200,
        turnIntervalMaxMs = 6400,
        turnJitterDegrees = 24.0,
        turnTowardCenterWeight = 0.14,
        zoneRadiusRatio = 1.0,
        maxTravelRadius = 2200.0,
        updateIntervalMs = 100,
        broadcastIntervalMs = 250,
        broadcastUpdates = true
    }
}

Config.Zones.tornado = {
    { name = 'Grapeseed', coords = vec3(2468.5, 4781.9, 34.6), radius = 2100.0 },
    { name = 'Sandy Shores', coords = vec3(1735.8, 3298.1, 41.1), radius = 2400.0 },
    { name = 'Great Chaparral', coords = vec3(-104.3, 1920.6, 196.9), radius = 2200.0 },
    { name = 'Paleto Bay', coords = vec3(-160.0, 6225.0, 30.0), radius = 2000.0 },
    { name = 'Mount Chiliad', coords = vec3(450.0, 5560.0, 800.0), radius = 2400.0 },
    { name = 'Raton Canyon', coords = vec3(-150.0, 4415.0, 100.0), radius = 2200.0 }
}

Config.ClientFx.tornadoParticle = {
    enabled = true,
    asset = 'scr_rcbarry2',
    effect = 'scr_rcbarry2_trail',
    scale = 3.4,
    heightOffset = 2.5,
    heightOffsets = { 2.5, 10.0, 18.0 },
    scales = { 3.8, 2.7, 1.8 },
    farClipDistance = 500.0,
    debrisEffect = 'scr_fbi_falling_debris',
    debrisBurstScale = 1.55,
    debrisBurstRadius = 30.0,
    debrisBurstIntervalMs = 1200
}

Config.ClientFx.tornadoFunnel = {
    enabled = true,
    asset = 'core',
    effect = 'ent_amb_smoke_foundry',
    effects = {
        'ent_amb_smoke_foundry'
    },
    layers = 120,
    baseRadius = 1.0,
    topRadius = 4.5,
    baseHeight = -1.2,
    topHeight = 200.0,
    baseScale = 2.6,
    topScale = 8.0,
    swirlDegreesPerLayer = 55.0,
    rotationSpeed = 1.8,
    refreshIntervalMs = 250,
    farClipDistance = 500.0,
    maxHandles = 40,
    innerFillCount = 6,
    topCloudEffect = 'ent_amb_smoke_foundry',
    topCloudScale = 7.8,
    topCloudHeight = 145.0,
    drawSolidFunnel = false,
    drawLayers = 120,
    drawBaseRadius = 30.0,
    drawTopRadius = 3.0,
    drawBaseHeight = 2.0,
    drawTopHeight = 222.0,
    drawSwirlRadius = 4.8,
    drawSwirlSpeed = 4.0,
    drawAlphaBase = 240,
    drawAlphaTop = 28,
    drawColor = { r = 60, g = 60, b = 60 },
    drawConeShell = false,
    drawSegments = 30,
    drawShellAlpha = 125,
    drawShellColor = { r = 52, g = 52, b = 52 },
    drawLineFunnel = false,
    drawLineCount = 26,
    drawLineAlpha = 140,
    drawLineColor = { r = 95, g = 95, b = 95 },
    drawCenterBeacon = false,
    drawBeaconColor = { r = 220, g = 220, b = 220 },
    drawBeaconAlpha = 80,
    drawBeaconScale = 15.5,
    drawVolumetricCloud = false,
    volumetricBands = 6,
    volumetricPuffsPerBand = 6,
    volumetricAlphaBase = 60,
    volumetricAlphaTop = 34,
    volumetricColor = { r = 70, g = 70, b = 70 },
    volumetricDrift = 0.55
}

Config.ClientFx.tornadoInteraction = {
    enabled = true,
    maxDistance = 260.0,
    forceIntervalMs = 70,
    closeRangeDistance = 30.0,
    extremeCoreDistance = 10.0,
    damageTickMs = 1600,
    player = {
        enabled = true,
        maxDistance = 40.0,
        maxPull = 6.25,
        maxLift = 3.35,
        maxSpin = 1.95,
        pullVelocity = 8.5,
        spinVelocity = 4.1,
        liftVelocity = 7.8,
        groundedLiftVelocity = 3.4,
        minVerticalVelocity = 2.2,
        maxVerticalVelocity = 14.0,
        velocityPreserveFactor = 0.45,
        ragdollThreshold = 0.10,
        liftedRagdollThreshold = 0.06,
        ragdollTimeMs = 2200,
        maintainRagdollIntervalMs = 280,
        releaseDistance = 18.0,
        releaseRearmDistance = 62.0,
        releaseForceScaleThreshold = 0.82,
        releaseAfterMs = 1750,
        releaseCooldownMs = 4200,
        releaseOutVelocity = 42.0,
        releaseUpVelocity = 11.5,
        releaseSpinVelocity = 5.4,
        releaseVelocityPreserveFactor = 0.10,
        velocityClamp = 38.0
    },
    peds = {
        enabled = true,
        searchRadius = 40.0,
        sweepIntervalMs = 350,
        maxSweepCount = 10,
        maxPull = 2.45,
        maxLift = 0.86,
        maxSpin = 0.90,
        pullVelocity = 4.8,
        spinVelocity = 2.0,
        liftVelocity = 4.6,
        groundedLiftVelocity = 1.8,
        minVerticalVelocity = 1.2,
        maxVerticalVelocity = 9.0,
        velocityPreserveFactor = 0.52,
        ragdollThreshold = 0.18,
        ragdollTimeMs = 1800,
        velocityClamp = 20.0
    },
    camera = {
        enabled = true,
        shakeName = 'SKY_DIVING_SHAKE',
        baseAmplitude = 0.10,
        maxAmplitude = 0.52,
        updateIntervalMs = 120
    },
    sound = {
        enabled = true,
        maxDistance = 260.0,
        baseVolume = 0.02,
        maxVolume = 0.26,
        lowpassHz = 420,
        highpassHz = 36,
        centerBoostDistance = 70.0
    },
    vehicle = {
        enabled = true,
        maxDistance = 30.0,
        sweepRadius = 40.0,
        sweepIntervalMs = 450,
        maxSweepCount = 8,
        maxLift = 6.00,
        maxPull = 8.6,
        maxSpin = 4.80,
        pullVelocity = 10.4,
        spinVelocity = 6.4,
        liftVelocity = 7.4,
        groundedLiftVelocity = 4.6,
        minVerticalVelocity = 1.4,
        maxVerticalVelocity = 15.5,
        velocityPreserveFactor = 0.58,
        releaseDistance = 18.0,
        releaseRearmDistance = 40.0,
        releaseForceScaleThreshold = 0.82,
        releaseAfterMs = 3400,
        releaseCooldownMs = 4200,
        releaseOutVelocity = 42.0,
        releaseUpVelocity = 15.0,
        releaseSpinVelocity = 8.0,
        releaseVelocityPreserveFactor = 0.08,
        velocityClamp = 58.0
    },
    debrisPool = {
        enabled = true,
        maxDistance = 100.0,
        poolSizeNear = 16,
        poolSizeMid = 10,
        poolSizeFar = 6,
        updateIntervalMs = 250,
        modelNames = {
            'prop_rub_tyre_01',
            'prop_trafficcone_01a',
            'prop_boxpile_06b',
            'prop_crate_11e',
            'prop_cardbordbox_04a',
            'prop_bin_08open',
            'prop_bucket_02a',
            { name = 'a_c_cow', entityType = 'ped' }
        },
        spawnRadius = 30.0,
        minHeight = 2.0,
        maxHeight = 28.0,
        orbitSpeed = 1.4,
        riseSpeed = 6.8,
        despawnHeight = 32.0,
        collision = false
    }
}

Disasters.tornado = {
    key = 'tornado',
    label = 'Tornado Warning',
    announcement = 'A tornado warning is in effect. Take cover immediately and avoid open roads near the impact corridor.',
    weather = 'THUNDER',
    rainLevel = 1.00,
    windSpeed = 1.00,
    duration = { min = 10, max = 18 },
    cooldownMinutes = 80,
    weight = 5,
    hazard = 'tornado',
    transition = {
        inMinutes = 2,
        outMinutes = 2
    },
    requiresZone = 'tornado'
}
